In [10]:
import pandas as pd

In [13]:
# Train
df = pd.read_csv('hotspot_train_classes.csv')

In [14]:
df[df['Hotspot'] == 0]

                                                filename  Hotspot
1520   imgFC142_png_jpg.rf.419ef0b3d7045c465ff4d7172f...        0
1521   imgFC142_png_jpg.rf.9865ffb37de529de4b5be52202...        0
1525   imgFC142_png_jpg.rf.224186de84bda9b5c59259c82c...        0
1540   imgFC130_png_jpg.rf.04951be914ece34c4bbb0cb685...        0
1551   imgFC142_png_jpg.rf.ac3d380e4a076c8bd5639d2103...        0
...                                                  ...      ...
14472  imgFC130_png_jpg.rf.b77b3f9e3a624bf46927b44fa5...        0
14475  IR_0246_jpg.rf.45fcc0e6b15de76c375f4cd23ff1545...        0
14503  imgFC130_png_jpg.rf.306946d961d012c060d87b8c4d...        0
14614  imgFC139_png_jpg.rf.719eb59cb469cf71ace385c34c...        0
14640  imgFC139_png_jpg.rf.924f256bcd47829d820e33c768...        0

[70 rows x 2 columns]

In [15]:
# Test

In [16]:
df = pd.read_csv('hotspot_test_classes.csv')

In [17]:
df[df['Hotspot'] == 0]

Empty DataFrame
Columns: [filename, Hotspot]
Index: []

In [18]:
# Valid

In [20]:
df = pd.read_csv('hotspot_valid_classes.csv')
df[df['Hotspot'] == 0]

Empty DataFrame
Columns: [filename, Hotspot]
Index: []